export const ActionTypes = {
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",
    LOGIN : "LOGIN",
    ADD_USER : "ADD_USER",
    UPDATE_USER : "UPDATE_USER",
    FORM_SUBMISSION_STATUS : "FORM_SUBMISSION_STATUS", 
}